body_acc_x_train <- read.fwf('C:\\UCI HAR Dataset\\train\\Inertial Signals\\body_acc_x_train.txt', widths=c(14))
body_acc_y_train <- read.fwf('C:\\UCI HAR Dataset\\train\\Inertial Signals\\body_acc_y_train.txt', widths=c(14))
body_acc_z_train <- read.fwf('C:\\UCI HAR Dataset\\train\\Inertial Signals\\body_acc_z_train.txt', widths=c(14))
body_gyro_x_train <- read.fwf('C:\\UCI HAR Dataset\\train\\Inertial Signals\\body_gyro_x_train.txt', widths=c(14))
body_gyro_y_train <- read.fwf('C:\\UCI HAR Dataset\\train\\Inertial Signals\\body_gyro_y_train.txt', widths=c(14))
body_gyro_z_train <- read.fwf('C:\\UCI HAR Dataset\\train\\Inertial Signals\\body_gyro_z_train.txt', widths=c(14))
total_acc_x_train <- read.fwf('C:\\UCI HAR Dataset\\train\\Inertial Signals\\total_acc_x_train.txt', widths=c(14))
total_acc_y_train <- read.fwf('C:\\UCI HAR Dataset\\train\\Inertial Signals\\total_acc_y_train.txt', widths=c(14))
total_acc_z_train <- read.fwf('C:\\UCI HAR Dataset\\train\\Inertial Signals\\total_acc_z_train.txt', widths=c(14))
trainInertialSignals <- cbind(body_acc_x_train, body_acc_y_train, body_acc_z_train, body_gyro_x_train, body_gyro_y_train, body_gyro_z_train, total_acc_x_train, total_acc_y_train, total_acc_z_train)
body_acc_x_test <- read.fwf('C:\\UCI HAR Dataset\\test\\Inertial Signals\\body_acc_x_test.txt', widths=c(14))
body_acc_y_test <- read.fwf('C:\\UCI HAR Dataset\\test\\Inertial Signals\\body_acc_y_test.txt', widths=c(14))
body_acc_z_test <- read.fwf('C:\\UCI HAR Dataset\\test\\Inertial Signals\\body_acc_z_test.txt', widths=c(14))
body_gyro_x_test <- read.fwf('C:\\UCI HAR Dataset\\test\\Inertial Signals\\body_gyro_x_test.txt', widths=c(14))
body_gyro_y_test <- read.fwf('C:\\UCI HAR Dataset\\test\\Inertial Signals\\body_gyro_y_test.txt', widths=c(14))
body_gyro_z_test <- read.fwf('C:\\UCI HAR Dataset\\test\\Inertial Signals\\body_gyro_z_test.txt', widths=c(14))
total_acc_x_test <- read.fwf('C:\\UCI HAR Dataset\\test\\Inertial Signals\\total_acc_x_test.txt', widths=c(14))
total_acc_y_test <- read.fwf('C:\\UCI HAR Dataset\\test\\Inertial Signals\\total_acc_y_test.txt', widths=c(14))
total_acc_z_test <- read.fwf('C:\\UCI HAR Dataset\\test\\Inertial Signals\\total_acc_z_test.txt', widths=c(14))
testInertialSignals <- cbind(body_acc_x_test, body_acc_y_test, body_acc_z_test, body_gyro_x_test, body_gyro_y_test, body_gyro_z_test, total_acc_x_test, total_acc_y_test, total_acc_z_test)
colnames(testInertialSignals) <- c('BodyAccX','BodyAccY','BodyAccZ','BodyGyroX','BodyGyroY','BodyGyroZ','TotalAccX','TotalAccY','TotalAccZ')
colnames(trainInertialSignals) <- c('BodyAccX','BodyAccY','BodyAccZ','BodyGyroX','BodyGyroY','BodyGyroZ','TotalAccX','TotalAccY','TotalAccZ')
testUsers <- read.fwf('C:\\UCI HAR Dataset\\test\\subject_test.txt', widths=c(2))
test <- cbind(testUsers, testInertialSignals)
trainUsers <- read.fwf('C:\\UCI HAR Dataset\\train\\subject_train.txt', widths=c(2))
train <- cbind(trainUsers, trainInertialSignals)
colnames(train)[1] <- 'User'
colnames(test)[1] <- 'User'
trainActivities <- read.fwf('C:\\UCI HAR Dataset\\train\\y_train.txt', widths=c(1))
testActivities <- read.fwf('C:\\UCI HAR Dataset\\test\\y_test.txt', widths=c(1))
train2 <- cbind(trainActivities, train)
test2 <- cbind(testActivities, test)
colnames(train2)[1] <- 'Activity'
colnames(test2)[1] <- 'Activity'
test4 <- mutate(test2, Activity2 = ifelse( (Activity == 3), 'Walking_Downstairs', ifelse ( (Activity == 4), 'Sitting', ifelse((Activity == 1), 'WALKING', ifelse((Activity == 2), 'Walking_Upstairs', ifelse((Activity == 5), 'Standing', ifelse((Activity == 6), 'Laying',  NA )))))))
train4 <- mutate(train2, Activity2 = ifelse( (Activity == 3), 'Walking_Downstairs', ifelse ( (Activity == 4), 'Sitting', ifelse((Activity == 1), 'WALKING', ifelse((Activity == 2), 'Walking_Upstairs', ifelse((Activity == 5), 'Standing', ifelse((Activity == 6), 'Laying',  NA )))))))
t <- read.table("C:\\UCI HAR Dataset\\train\\X_train.txt")
t2 <- read.table("C:\\UCI HAR Dataset\\test\\X_test.txt")
features <- read.table("C:\\UCI HAR Dataset\\features.txt")
colnames(t) <- features[, 2]
colnames(t2) <- features[, 2]
test <- cbind(test4, t2)
train <- cbind(train4, t)
final <- rbind(train, test)

